[package]
name = "lumenza"
version = "0.2.0"
edition = "2021"

[lib]
name = "lumenza"
doctest = false

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled", "chrono"] }
tempdir = "0.3"
walkdir = "2.3"
mime_guess = "2.0"
